unittests:
        tags:
                - aictx
        image: continuumio/miniconda3:latest
        script:
                - ./NetworksPython/requirements_conda.sh
                - pip install -r NetworksPython/requirements.txt
                - pip install pytest
                - pytest NetworksPython
        
