unittests:
        image: continuumio/miniconda3:latest
        tags:
                - python
                - aiCTX
        script:
                - conda create --name py36_test
                - conda activate py36_test
                - ./requirements_conda.sh
                - pip install -r requirements.txt
                - pip install pytest
                - pip install .
                - pytest 
        
