unit_tests:
  image: aictx/ci-python-arch:latest
  tags:
    - python
    - aiCTX

  before_script:
    - pip install --upgrade pip
    - pip install . --no-cache-dir


  script:
    - pytest -v tests

nest_tests:
  image: aictx/ci-python-arch:latest
  tags:
    - python
    - aiCTX

  before_script:
    - pip install --upgrade pip
    - pip install . --no-cache-dir


  script:
    - pytest -v test_nest

