stages:
  - test
  - build
  - deploy

unit_tests:
  stage: test
  image: aictx/ci-python-arch:latest
  tags:
    - python
    - aiCTX

  before_script:
    - pip install --upgrade pip
    - pip install .[all] --no-cache-dir


  script:
    - pytest -v tests

nest_tests:
  stage: test
  when: manual
  allow_failure: true
  image: aictx/ci-python-arch:latest
  tags:
    - python
    - aiCTX

  before_script:
    - pip install --upgrade pip
    - pip install .[all] --no-cache-dir


  script:
    - pytest -v test_nest

documentation_linting:
  stage: test
  allow_failure: true
  image: aictx/ci-python-arch:latest
  tags:
    - python
    - aiCTX

  before_script:
    - pip install --upgrade pip
    - pip install .[all] --no-cache-dir

  script:
    - sphinx-build -n -b dummy docs docs/_build/html

docs_build:
  stage: build
  allow_failure: true
  image: aictx/ci-python-arch:latest
  tags:
    - python
    - aiCTX

  before_script:
    - pip install sphinx_rtd_theme
    - pip install --upgrade pip
    - pip install .[all] --no-cache-dir

  script:
    - sphinx-build -b html docs docs/_build/html

  artifacts:
    paths:
      - docs/_build/html
    expire_in: 15 mins

pages:
  stage: deploy
  only:
    - master

  allow_failure: true
  image: aictx/ci-python-arch:latest
  tags:
    - python
    - aiCTX

  dependencies:
    - docs_build

  script:
    - mv docs/_build/html/ public/

  artifacts:
    paths:
      - public

