stages:
  - test
  - build
  - deploy

unit_tests:
  stage: test
  image: aictx/ci-python-arch:latest

  tags:
    - aiCTX
    - python

  before_script:
    - pip install --upgrade pip
    - pip install .[all] --no-cache-dir

  script:
    - pytest -v tests -n 4

nest_tests:
  stage: test
  image: aictx/ci-python-arch:latest

  tags:
    - aiCTX
    - python

  before_script:
    - pip install --upgrade pip
    - pip install .[all] --no-cache-dir

  script:
      - source /usr/bin/nest_vars.sh
      - pytest -v test_nest -n 4

documentation_linting:
  stage: test
  allow_failure: true
  image: aictx/ci-python-arch:latest

  tags:
    - aiCTX
    - python

  before_script:
    - pip install --upgrade pip
    - pip install .[all] --no-cache-dir

  script:
    - sphinx-build -n -b dummy docs docs/_build/html

docs_build:
  stage: build
  allow_failure: true
  image: aictx/ci-python-arch:latest

  tags:
    - aiCTX
    - python

  before_script:
    - pip install --upgrade pip
    - pip install .[all] --no-cache-dir

  script:
    - sphinx-build -b html docs docs/_build/html

  artifacts:
    paths:
      - docs/_build/html
    expire_in: 15 mins

dist_build:
  stage: build
  image: aictx/ci-python-arch:latest

  tags:
    - aiCTX
    - python

  dependencies:
    - unit_tests
    - nest_tests

  before_script:
    - pip install --upgrade pip
    - pip install wheel

  script:
    - python setup.py sdist
    - python setup.py bdist_wheel

  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  only:
    - master

  tags:
    - aiCTX
    - python

  allow_failure: true
  image: aictx/ci-python-arch:latest

  dependencies:
    - docs_build

  script:
    - mv docs/_build/html/ public/

  artifacts:
    paths:
      - public

pypi_deploy:
  stage: deploy
  when: manual
  image: aictx/ci-python-arch:latest

  tags:
    - aiCTX
    - python

  only:
    - master

  dependencies:
    - dist_build

  before_script:
    - pip install --upgrade pip
    - pip install -U twine

  script:
    - python -m twine upload dist/*
