unittests:
        image: continuumio/miniconda3:latest
        script:
                - ./requirements_conda.sh
                - pip install -r requirements.txt
                - pip install pytest
                - pytest NetworksPython
        
