image: continuumio/miniconda3:latest

before_script:
        - export PIP_CACHE_DIR="/opt/cache/pip"


unittests:
        tags:
                - python
                - aiCTX
        script:
                - ./requirements_conda.sh
                - pip install -r requirements.txt
                - pip install pytest
                - pip install .
                - pytest 
        
