stages:
  - testing
  - building
  - packaging

unit_tests:
  stage: testing
  image: aictx/ci-python-arch:latest
  tags:
    - python
    - aiCTX

  before_script:
    - pip install --upgrade pip
    - pip install .[all] --no-cache-dir


  script:
    - pytest -v tests

nest_tests:
  stage: testing
  when: manual
  allow_failure: true
  image: aictx/ci-python-arch:latest
  tags:
    - python
    - aiCTX

  before_script:
    - pip install --upgrade pip
    - pip install .[all] --no-cache-dir


  script:
    - pytest -v test_nest

documentation_linting:
  stage: testing
  allow_failure: true
  image: aictx/ci-python-arch:latest
  tags:
    - python
    - aiCTX

  before_script:
    - pip install --upgrade pip
    - pip install .[all] --no-cache-dir

  script:
    - sphinx-build -n -b dummy docs docs/_build/html

docs_build:
  stage: building
  allow_failure: true
  image: aictx/ci-python-arch:latest
  tags:
    - python
    - aiCTX

  before_script:
    - pip install sphinx_rtd_theme
    - pip install --upgrade pip
    - pip install .[all] --no-cache-dir

  script:
    - sphinx-build -b html docs docs/_build/html

  artifacts:
    - docs/build/_html
