unittests:
        image: continuumio/miniconda3:latest
        tags:
                - python
                - aiCTX
        script:
                - ./requirements_conda.sh
                - pip install -r requirements.txt
                - pip install pytest
                - pip install
                - pytest 
        
