channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - brian2
  - cudatoolkit
  - matplotlib
  - nest-simulator
  - numba
  - numpy
  - pandas
  - pyqt
  - pytest>=6.0
  - python>=3.6
  - pytorch>=1.0
  - qt
  - scipy
  - setuptools
  - torchvision
  - tqdm
  - jax
  - jaxlib
